import { app, shell } from "electron"
import path from "path"
import { autoUpdater } from "electron-updater"
import { ReleaseNotesManager } from "../update/ReleaseNotesManager"
import type { AppState } from "../main"

export function setupAutoUpdater(appState: AppState): void {
  autoUpdater.autoDownload = false
  autoUpdater.autoInstallOnAppQuit = false  // Manual install only via button

  // Default to latest (stable) channel - matches latest.yml generated by electron-builder
  autoUpdater.channel = 'latest'
  console.log(`[AutoUpdater] Channel: ${autoUpdater.channel}`)

  autoUpdater.on("checking-for-update", () => {
    console.log("[AutoUpdater] Checking for update...")
    appState.broadcast("update-checking")
  })

  autoUpdater.on("update-available", async (info) => {
    console.log("[AutoUpdater] Update available:", info.version)
    appState.updateAvailable = true

    // Fetch structured release notes
    const releaseManager = ReleaseNotesManager.getInstance();
    const notes = await releaseManager.fetchReleaseNotes(info.version);

    // Notify renderer that an update is available with parsed notes if available
    appState.broadcast("update-available", {
      ...info,
      parsedNotes: notes
    })
  })

  autoUpdater.on("update-not-available", (info) => {
    console.log("[AutoUpdater] Update not available:", info.version)
    appState.broadcast("update-not-available", info)
  })

  autoUpdater.on("error", (err) => {
    console.error("[AutoUpdater] Error:", err)
    // Include more details in the error message for debugging
    const errorMessage = err.message || err.toString() || 'Unknown update error'
    appState.broadcast("update-error", errorMessage)
  })

  autoUpdater.on("download-progress", (progressObj) => {
    let log_message = "Download speed: " + progressObj.bytesPerSecond
    log_message = log_message + " - Downloaded " + progressObj.percent + "%"
    log_message = log_message + " (" + progressObj.transferred + "/" + progressObj.total + ")"
    console.log("[AutoUpdater] " + log_message)
    appState.broadcast("download-progress", progressObj)
  })

  autoUpdater.on("update-downloaded", (info) => {
    console.log("[AutoUpdater] Update downloaded:", info.version)
    // Notify renderer that update is ready to install
    appState.broadcast("update-downloaded", info)
  })

  // Start checking for updates with a 10-second delay
  setTimeout(() => {
    if (process.env.NODE_ENV === "development") {
      console.log("[AutoUpdater] Development mode: Skipping auto check (use manual button)");
    } else {
      autoUpdater.checkForUpdatesAndNotify().catch(err => {
        console.error("[AutoUpdater] Failed to check for updates:", err);
      });
    }
  }, 10000);
}

export async function checkForUpdatesManual(appState: AppState): Promise<void> {
  try {
    console.log('[AutoUpdater] Checking for updates manually via GitHub API...');
    const releaseManager = ReleaseNotesManager.getInstance();
    // Fetch latest release
    const notes = await releaseManager.fetchReleaseNotes('latest');

    if (notes) {
      const currentVersion = app.getVersion();
      const latestVersionTag = notes.version; // e.g., "v1.2.0" or "1.2.0"
      const latestVersion = latestVersionTag.replace(/^v/, '');

      console.log(`[AutoUpdater] Manual Check: Current=${currentVersion}, Latest=${latestVersion}`);

      if (isVersionNewer(appState, currentVersion, latestVersion)) {
        console.log('[AutoUpdater] Manual Check: New version found!');
        appState.updateAvailable = true;

        // Mock an info object compatible with electron-updater
        const info = {
          version: latestVersion,
          files: [] as any[],
          path: '',
          sha512: '',
          releaseName: notes.summary,
          releaseNotes: notes.fullBody
        };

        // Notify renderer
        appState.broadcast("update-available", {
          ...info,
          parsedNotes: notes
        });
      } else {
        console.log('[AutoUpdater] Manual Check: App is up to date.');
        appState.broadcast("update-not-available", { version: currentVersion });
      }
    }
  } catch (err) {
    console.error('[AutoUpdater] Manual update check failed:', err);
  }
}

export function isVersionNewer(appState: AppState, current: string, latest: string): boolean {
  // EC-01 fix: strip pre-release suffixes (e.g. "2.1.0-beta.1" → "2.1.0")
  // before splitting so Number() never returns NaN on comparison.
  const stripPre = (v: string) => v.replace(/-.*$/, '');
  const c = stripPre(current).split('.').map(Number);
  const l = stripPre(latest).split('.').map(Number);

  for (let i = 0; i < 3; i++) {
    const cv = c[i] || 0;
    const lv = l[i] || 0;
    if (lv > cv) return true;
    if (lv < cv) return false;
  }
  return false;
}

export async function quitAndInstallUpdate(appState: AppState): Promise<void> {
  console.log('[AutoUpdater] quitAndInstall called - applying update...')

  // On macOS, unsigned apps can't auto-restart via quitAndInstall
  // Workaround: Open the folder containing the downloaded update so user can install manually
  if (process.platform === 'darwin') {
    try {
      // Get the downloaded update file path (e.g., .../Pika-1.0.9-mac.zip)
      const updateFile = (autoUpdater as any).downloadedUpdateHelper?.file
      console.log('[AutoUpdater] Downloaded update file:', updateFile)

      if (updateFile) {
        const updateDir = path.dirname(updateFile)
        // Open the directory containing the update in Finder
        await shell.openPath(updateDir)
        console.log('[AutoUpdater] Opened update directory:', updateDir)

        // Quit the app so user can install new version
        setTimeout(() => app.quit(), 1000)
        return
      }
    } catch (err) {
      console.error('[AutoUpdater] Failed to open update directory:', err)
    }
  }

  // Fallback to standard quitAndInstall (works on Windows/Linux or if signed)
  setImmediate(() => {
    try {
      autoUpdater.quitAndInstall(false, true)
    } catch (err) {
      console.error('[AutoUpdater] quitAndInstall failed:', err)
      app.exit(0)
    }
  })
}

export async function checkForUpdates(appState: AppState): Promise<void> {
  console.log('[AutoUpdater] Manual check for updates requested')
  try {
    // In development mode, use manual GitHub API check (electron-updater skips in dev)
    if (process.env.NODE_ENV === "development") {
      await checkForUpdatesManual(appState)
    } else {
      await autoUpdater.checkForUpdatesAndNotify()
    }
  } catch (err: any) {
    console.error('[AutoUpdater] checkForUpdates failed:', err)
    const errorMessage = err.message || err.toString() || 'Update check failed'
    appState.broadcast("update-error", errorMessage)
  }
}

export function downloadUpdate(appState: AppState): void {
  console.log('[AutoUpdater] Starting download...')
  try {
    // Errors during download are surfaced via autoUpdater.on("error") which
    // already broadcasts "update-error". Do not broadcast here to avoid duplicates.
    autoUpdater.downloadUpdate().catch(err => {
      console.error('[AutoUpdater] downloadUpdate failed:', err)
    })
  } catch (err: any) {
    console.error('[AutoUpdater] downloadUpdate exception:', err)
  }
}
